ekreative_redmine_homepage:
    path:     /hello/{name}
    defaults: { _controller: EkreativeRedmineBundle:Default:index }

login_route:
    path:     /login
    defaults: { _controller: EkreativeRedmineBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

projects:
    path: /
    defaults: { _controller: EkreativeRedmineBundle:Redmine:index }

issues_per_project:
    path: /issues/{projectId}
    defaults: { _controller: EkreativeRedmineBundle:Redmine:getIssuesPerProject }

log_time:
    path: /project/{projectId}/logtime
    defaults: { _controller: EkreativeRedmineBundle:Redmine:logTime }

track:
    path: /track
    defaults: { _controller: EkreativeRedmineBundle:Redmine:track }
